---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: wda
  namespace: default
  labels: 
      name: wda
      keel.sh/policy: force
      keel.sh/trigger: poll      
      # keel.sh/approvals: "1"
  annotations:
      keel.sh/pollSchedule: "@every 5s"
      # keel.sh/notify: chan1,chan2
spec:
  replicas: 1
  template:
    metadata:
      name: wda
      labels:
        app: wda     
    spec:      
      containers:                    
        - image: karolisr/webhook-demo:alpha   
          imagePullPolicy: Always            
          name: wda
          command: ["/bin/webhook-demo"]
          ports:
            - containerPort: 8090       
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8090
            initialDelaySeconds: 30
            timeoutSeconds: 10
          securityContext:
            privileged: true         